### PR TITLE
Remove identity closure

### PR DESCRIPTION
**Pull request by avkrotov**

### CODE REVIEW

**Comment by IanWhitney** [comment]
Why?

**Comment by avkrotov** [comment]
It is unnecessary. map calls a function that does nothing but calls another function. It is just a code cleanup.

**Comment by IanWhitney** [comment]
Great. Can you amend your commit message to include that reasoning? It will make later contributors a lot happier. 

https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#commit-messages

**Comment by IanWhitney** [comment]
Closing for now. If this can be updated with a commit message that meets Exercism's contribution guidelines then I'm all for merging it. Thanks.

**Pull request closed without merging**
