### PR TITLE
Add rectangles exercise

### PR DESCRIPTION
**Pull request by pminten**

### CODE REVIEW

**Comment by EduardoBautista** [comment]
Some of the tests are missing the ignore flag (`#[ignore]`) to be consistent with the rest of the exercises.

**Comment by pminten** [comment]
Added the #[ignore] flags.

**Comment by EduardoBautista** [comment]
This looks good to me.  If you can't think of anything else to improve we should merge this.

**Comment by pminten** [comment]
Thanks for the review.

**Pull request merged**
