### PR TITLE
Improve tests in grade school.

### PR DESCRIPTION
**Pull request by stevejb71**
Make names more explicit (to show that values are returned sorted from
grades and grade).
Add more tests for the empty cases.

### CODE REVIEW

**Comment by EduardoBautista** [comment]
@kytrinyx How often do test cases differ from other languages?

**Comment by kytrinyx** [comment]
@EduardoBautista pretty often. We're trying to get better at two things:

1. Making sure that great test cases spread into all the languages (https://github.com/exercism/todo/issues/13), and
2. Making sure problems in each language follows that language's idioms and patterns

**Comment by EduardoBautista** [comment]
Well, these tests look fine to me.  @kytrinyx so is it OK to merge this in your opinion even though the tests are a bit different from other languages?

**Comment by kytrinyx** [comment]
@EduardoBautista Yepp, go for it. As long as it won't be confusing when they look at the README, this is totally fine.

**Comment by EduardoBautista** [comment]
Thanks @stevejb71!

**Pull request merged**
