### PR TITLE
PascalsTriangle: two more test cases!

### PR DESCRIPTION
**Pull request by niklasad1**
Hi,
Added two more test cases 
/Niklas A

### CODE REVIEW

**Comment by IanWhitney** [comment]
Thanks! 

A couple of questions.

- What edge cases do these tests cover that the existing tests don't?
- Are these tests only useful for Rust, or should we add them to the [canonical test suite](https://github.com/exercism/x-common/blob/master/exercises/pascals-triangle/canonical-data.json) that all language tracks follow?

**Comment by niklasad1** [comment]
Hmm, they are not testing any edge case what I'm aware but I thought it that people can get lucky or hardcode in the answer which is much harder with 21 rows ;) 

Use them if you want to but the existing tests may be sufficient.

**Comment by petertseng** [comment]
I have no opinion on whether this track should have these tests, so I'm acknowledging that I'm being weak, evading the question, and passing the buck by deferring to x-common. If the same test cases are added to x-common, the Rust track will take them.

It looks like from https://github.com/exercism/x-common/pull/362 that some tracks test 20 but it was not made standard since once it works for four rows it probably works for subsequent rows.

Perhaps going up to five or more helps us because the fifth row is the first time a value appears that does not have 1 as one of its addends. That can be an argument for adding five (or some higher number) to x-common.

I will be happy to post the same opinion in x-common.

**Comment by petertseng** [comment]
We look forward to seeing these cases in x-common at https://github.com/exercism/x-common/blob/master/exercises/pascals-triangle/canonical-data.json and would like to see it merged there before merging here.

**Comment by petertseng** [comment]
Let's reopen this PR when it is merged in x-common!

**Pull request closed without merging**
