### PR TITLE
SETUP.md: move to exercises/TRACK_HINTS.md

### PR DESCRIPTION
**Pull request by petertseng**
As https://github.com/exercism/exercism.io/issues/3240 states, we would
like to rename SETUP.md.

https://github.com/exercism/trackler/pull/17 has added the necessary
support for TRACK_HINTS.md, so we can now move this file.

### CODE REVIEW

**Comment by petertseng** [comment]
Confirmed via https://github.com/exercism/xhaskell/pull/462 that exercises/TRACK_HINTS.md does in fact work, so this has made brave enough to merge this without adding a backup SETUP.md as was done in https://github.com/exercism/xhaskell/pull/463. But if any of y'all want it I'm happy to approve your PR adding it.

**Comment by petertseng** [comment]
Hello everyone, this has been:

* added to trackler: https://github.com/exercism/trackler/commit/d2981a39c1e4407fd50ee04e3434de720cbe9d86
* added to the site: https://github.com/exercism/exercism.io/commit/daefe8cd262aece9bbacf3d4618d6553e03279d1
* deployed: http://exercism.io/version

So, now is a great time to check whether `exercism fetch rust <some-exercise>` still provides a `README.md` including the contents of our `exercises/TRACK_HINTS.md`. If it does not, we should see if there is a way to get it back.

**Comment by petertseng** [comment]
Hello, I can't check using the `exercism` binary right now, but I can check http://x.exercism.io/v2/exercises/rust/hello-world and see that our TRACK_HINTS are included, so we appear to be good.

**Comment by IanWhitney** [comment]
Fetched `forth`and got the README.

**Pull request merged**
