### PR TITLE
Add implementation of "allergies" exercise.

### PR DESCRIPTION
**Pull request by adolfosilva**
Hi folks,

Here is a Rust implementation of the Python [allergies](https://github.com/exercism/xpython/tree/master/allergies) exercise.

Would appreciate any feedback. :smile:

### CODE REVIEW

**Comment by EduardoBautista** [comment]
Hello!  Thanks for helping out!  Here are some things that should be changed:

1. The `allergies.rs` file should be renamed to `example.rs`.
2. Tests should have the ignore flag `#[ignore]` enabled, except for the first one.
3. The exercise should be added to `config.json`: https://github.com/exercism/xrust/blob/master/config.json
4. We currently do not include the `src/lib.rs` file in any of the other exercises, so that should be removed as well.

@pminten @etrepum any feedback on the actual code itself?  I am still learning Rust so I am not too familiar of any conventions/best practices.

**Comment by EduardoBautista** [comment]
@adolfosilva Looks like there is a merge conflict in the config.json file.  Can you resolve it please?

**Comment by adolfosilva** [comment]
Done.

**Comment by kytrinyx** [comment]
Thanks! Would you also mind squashing the commits into one? It helps keep the history more manageable.

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by adolfosilva** [comment]
@kytrinyx No problem.

**Comment by kytrinyx** [comment]
This looks good to me. I'll let one of the rust track maintainers do the merge. Thanks!

**Comment by EduardoBautista** [comment]
Looks good to me as well!

**Pull request merged**
