### PR TITLE
Added hexadecimal exercise.

### PR DESCRIPTION
**Pull request by razielgn**
:cherry_blossom:

### CODE REVIEW

**Comment by EduardoBautista** [comment]
The asserts should probably be in separate tests, here is an example in Ruby:

https://github.com/exercism/xruby/blob/master/hexadecimal/hexadecimal_test.rb

**Comment by razielgn** [comment]
Yes, it's better now. :smiley: :+1:

**Comment by EduardoBautista** [comment]
Looks good!  Thanks!

**Comment by razielgn** [comment]
Thank you. :)

**Pull request merged**
