### PR TITLE
Provide necessary files for custom exercises

### PR DESCRIPTION
**Pull request by IanWhitney**
Track-only exercises need to provide their own metadata.yml and
description.md files. Previously I'd put everything into HINTS.md, but
that is no longer necessary or correct.

### CODE REVIEW

**Comment by IanWhitney** [comment]
Merging quick so that @kytrinyx can deploy. We're trying to make sure this whole "track-only" thing works.

https://twitter.com/kytrinyx/status/836284637693505537

**Comment by kytrinyx** [comment]
w00t! Thanks :heart:

**Comment by petertseng** [comment]
Retroactive approve.

**Comment by IanWhitney** [comment]
Our Rust-only Luhn exercises have been deployed and they work!

http://exercism.io/tracks/rust/exercises/luhn-trait
http://exercism.io/tracks/rust/exercises/luhn-from

**Pull request merged**
