### PR TITLE
Use Cargo for builds

### LINKED ISSUE #18: Modifying all exercises to work with cargo
It looks like cargo will be the preferred way to run tests going forward.  Since it comes with Rust, we should probably set up the exercises so that `cargo run` and `cargo test` can be used.  I can help by making the changes.

### PR DESCRIPTION
**Pull request by EduardoBautista**
Continuing the work from: https://github.com/exercism/xrust/pull/26

@pminten I also included your bash script and fixed that compilation error.

Closes #18

### CODE REVIEW

**Comment by EduardoBautista** [comment]
Looking into the failure...

**Comment by EduardoBautista** [comment]
Looking into the failure...

**Comment by EduardoBautista** [comment]
Looking into the failure...

**Comment by EduardoBautista** [comment]
And we are green!

**Comment by etrepum** [comment]
Green! Woot :) Nice work!! :+1:

**Pull request merged**
