### PR TITLE
Detect false positive from `eq_ignore_ascii_case`

### PR DESCRIPTION
**Pull request by chancancode**

### CODE REVIEW

**Comment by EduardoBautista** [comment]
I think this is OK haha.  Not too familiar with greek letters.  I am assuming that `γ` is the lowercase version of `Γ` is that correct?

**Comment by chancancode** [comment]
Yes, it is based on another test case in the file:

```rust
#[test]
#[ignore]
fn test_unicode_anagrams() {
    // These words don't make sense, they're just greek letters cobbled together.
    let inputs = ["ΒΓΑ", "ΒΓΔ", "γβα"];
    let outputs: Vec<&str> = vec!["ΒΓΑ", "γβα"];
    assert_eq!(anagram::anagrams_for("ΑΒΓ", &inputs), outputs);
}
```

**Comment by EduardoBautista** [comment]
OK, looks good, thanks!

**Comment by chancancode** [comment]
In the ascii case, there are two tests about lowercase letters:

1. `Carthorse` is an anagram of `Orchestra`
2. `bAnana` is not an anagram of `banana`

This adds the second case to the unicode (greek letters) version

**Comment by kytrinyx** [comment]
Weird, it seems like (1) and (2) are incompatible with each other.

I guess the question boils down to whether or not anagrams are case insensitive or not. (I believe that they are, but I could probably be swayed by an argument against it).

**Comment by chancancode** [comment]
@kytrinyx I don't think they are incompatible. To be clear, the first case is expressing that anagrams are case-insensitive; and the second case is expressing that `banana` is not an anagram of `banana` (because they are the same word) and that the implementation should not be fooled simply because `bAnana` has an upper-case `A`.

**Comment by kytrinyx** [comment]
oh, hah. Yes, you're absolutely right. Thank you.

**Pull request merged**
